name: Build & Tests

on:
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
        - "**.md"
        - "docs/**"

jobs:
  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 15
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-build-${{ hashFiles('frontend/package-lock.json') }}
        restore-keys: |
          npm-build-${{ hashFiles('frontend/package-lock.json') }}
          npm-build-
          npm
    - name: Install dependencies
      run: |
        npm i --no-optional --no-audit --no-fund
      working-directory: ./frontend
    - name: Lint with eslint
      run: |
        npm run lint
      working-directory: ./frontend
# no tests are implemented right now
#    - name: Test with Jest
#      run: |
#        npm run test
#      working-directory: ./frontend
